name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go: ["1.24.x"]
    
    runs-on: ${{ matrix.os }}
    name: Tests (Go ${{ matrix.go }})
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
      
      - name: Verify dependencies
        run: |
          go mod tidy
      
      - name: Run tests with race detector
        run: go test -v -race ./...
  
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: true
      
      - name: Install linters
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: Code formatting
        run: |
          # Check formatting
          test -z "$(gofmt -s -l . | tee /dev/stderr)"
      
      - name: Static analysis
        run: |
          go vet ./...
          staticcheck ./...